[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Custom domain configuration
[[redirects]]
  from = "https://kctt-website.netlify.app/*"
  to = "https://globcorp.com/:splat"
  status = 301
  force = true

# Handle trailing slashes
[[redirects]]
  from = "/index"
  to = "/"
  status = 301

# Redirect www to non-www
[[redirects]]
  from = "https://www.globcorp.com/*"
  to = "https://globcorp.com/:splat"
  status = 301
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data:; connect-src 'self';"

# Cache static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"